---
title: "EDA"
author: "R Sangole"
output: 
  html_notebook: 
    highlight: zenburn
    theme: cerulean
    toc_float: yes
    toc: true
---

# Exploring full training dataset
```{r}
training_data %<>%
    mutate(text = str_replace_all(text,pattern = '[.]',replacement = ' '))

tidy_text <- training_data %>% 
    unnest_tokens(word,text,to_lower = F)
```

```{r}
data("stop_words")

tidy_text %<>% 
    anti_join(stop_words)
```

```{r}
tidy_text %>% 
    count(word,sort = T)
```

```{r}
tidy_text %>%
  count(word, sort = TRUE) %>%
  filter(n > 1e4) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```

```{r}
wordcloud2(tidy_text %>% count(word,sort = T),color = 'random-dark',fontFamily = 'arial')
```



# Trying sentiment analysis

```{r}
sentiments %>% sample_n(10)
```

```{r}
afinn <- get_sentiments('afinn')

DSID_sentiment <- tidy_text %>% 
    inner_join(afinn) %>% 
    group_by(dsid_id) %>% 
    summarize(mean_sentiment = mean(score))

histogram(~mean_sentiment,DSID_sentiment)
```

```{r message=FALSE, warning=FALSE}
bing <- get_sentiments('bing')
DSID_sentiment <- tidy_text %>% 
    inner_join(bing) %>% 
    group_by(dsid_id) %>% 
    count(sentiment) %>% 
    spread(sentiment,n)
training_data %>% 
    inner_join(DSID_sentiment) %>% 
    ggplot(aes(x=positive,y=negative))+
    geom_jitter(alpha=0.1)+
    coord_equal(ratio = 1,xlim = c(0,50))+
    scale_x_continuous(breaks = seq(0,50,10))+
    scale_y_continuous(breaks = seq(0,50,10))
```
```{r message=FALSE, warning=FALSE}
nrc <- get_sentiments('nrc')
DSID_sentiment <- tidy_text %>% 
    inner_join(nrc) %>% 
    group_by(dsid_id) %>%
    count(sentiment)
bwplot(sentiment~n,DSID_sentiment)
histogram(~n|sentiment,DSID_sentiment,nint = 30)
```

